#! /bin/sh


# auto start
killall -q latte-dock
sh /home/jaime/.config/polybar/launch.sh --blocks &
#killall -q picom &
killall -q sxhkd; sxhkd -c ~/.config/bspwm/sxhkdrc &
killall -q picom; picom -b --experimental-backends --config ~/.config/picom.conf&
dunst --config ~/.config/dunst/dunstrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focused_border_color "#89b4fa"
bspc config normal_border_color "#313244"
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a lattedock manage=off
# floating rules
bspc rule -a transmission state=floating
bspc rule -a dolphin state=floating
bspc rule -a Alacritty state=floating
bspc rule -a kate state=floating
bspc rule -a systemsettings state=floating
bspc rule -a heroic state=floating
bspc rule -a Lutris state=floating
bspc rule -a Steam state=floating
bspc rule -a Spotify state=floating
bspc rule -a gwenview state=floating
bspc rule -a stacer state=floating



# Kill if already running
# killall -9 picom sxhkd dunst flameshot touchegg
